Controllers/GiangViensController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UniSchedule.Models;

namespace UniSchedule.Controllers
{
    public class GiangViensController : Controller
    {
        private XepLichGiangVienEntities db = new XepLichGiangVienEntities();
        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            if (Session["MaVaiTro"] == null || (int)Session["MaVaiTro"] != 2)
            {
                // Không phải GiaoVu thì chuyển về trang login
                filterContext.Result = RedirectToAction("Login", "Home");
            }
            base.OnActionExecuting(filterContext);
        }
        // GET: GiangViens
        public ActionResult Index()
        {
            var giangViens = db.GiangViens
                .Include(g => g.Khoa)
                .Include(g => g.PhanCongGiangDays.Select(p => p.LopHocPhan)); // cần thiết để tính SoTinChi

            return View(giangViens.ToList());
        }

        // GET: GiangViens/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GiangVien giangVien = db.GiangViens.Find(id);
            if (giangVien == null)
            {
                return HttpNotFound();
            }
            return View(giangVien);
        }

        // GET: GiangViens/Create
        public ActionResult Create()
        {
            ViewBag.MaKhoa = new SelectList(db.Khoas, "MaKhoa", "TenKhoa");
            return View();
        }

        // POST: GiangViens/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaGV,TenGV,MaKhoa,Email,SoDienThoai")] GiangVien giangVien)
        {
            if (ModelState.IsValid)
            {
                db.GiangViens.Add(giangVien);
                TaiKhoan taiKhoan = new TaiKhoan
                {
                    TenDangNhap = giangVien.SoDienThoai,
                    MatKhau = "123abc",
                    MaGV = giangVien.MaGV,
                    MaVaiTro = 1
                };

                db.TaiKhoans.Add(taiKhoan);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            ViewBag.MaKhoa = new SelectList(db.Khoas, "MaKhoa", "TenKhoa", giangVien.MaKhoa);
            return View(giangVien);
        }


        // GET: GiangViens/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GiangVien giangVien = db.GiangViens.Find(id);
            if (giangVien == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaKhoa = new SelectList(db.Khoas, "MaKhoa", "TenKhoa", giangVien.MaKhoa);
            return View(giangVien);
        }

        // POST: GiangViens/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaGV,TenGV,MaKhoa,Email,SoDienThoai")] GiangVien giangVien)
        {
            if (ModelState.IsValid)
            {
                db.Entry(giangVien).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaKhoa = new SelectList(db.Khoas, "MaKhoa", "TenKhoa", giangVien.MaKhoa);
            return View(giangVien);
        }

        // GET: GiangViens/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GiangVien giangVien = db.GiangViens.Find(id);
            if (giangVien == null)
            {
                return HttpNotFound();
            }
            return View(giangVien);
        }

        // POST: GiangViens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            GiangVien giangVien = db.GiangViens.Find(id);
            db.GiangViens.Remove(giangVien);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniSchedule.Models;


namespace XepLichGiangVien.Controllers
{
    public class HomeController : Controller
    {
        private XepLichGiangVienEntities db = new XepLichGiangVienEntities();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(string tenDangNhap, string matKhau)
        {
            var taiKhoan = db.TaiKhoans.FirstOrDefault(t => t.TenDangNhap == tenDangNhap && t.MatKhau == matKhau);
            if (taiKhoan != null)
            {
                Session["TenDangNhap"] = taiKhoan.TenDangNhap;
                Session["MaVaiTro"] = taiKhoan.MaVaiTro;
                Session["MaGV"] = taiKhoan.MaGV;

                if (taiKhoan.MaVaiTro == 0)
                {
                    return RedirectToAction("GiaoVu", "Home");
                }
                else if (taiKhoan.MaVaiTro == 1)
                {
                    return RedirectToAction("GiangVien", "Home");
                }
                else if (taiKhoan.MaVaiTro == 2)
                {
                    return RedirectToAction("PhongDaoTao", "Home");
                }
            }
            else
            {
                ViewBag.Error = "Tên đăng nhập hoặc mật khẩu không đúng.";
                return View();
            }

            return View();
        }
        public ActionResult PhongDaoTao()
        {
            if (Session["MaVaiTro"] == null || (int)Session["MaVaiTro"] != 2)
            {
                return RedirectToAction("Login", "Home");
            }
            return View();
        }
        public ActionResult GiaoVu()
        {
            if (Session["MaVaiTro"] == null || (int)Session["MaVaiTro"] != 0)
            {
                return RedirectToAction("Login", "Home");
            }
            return View();
        }
        public ActionResult GiangVien()
        {
            if (Session["MaVaiTro"] == null || (int)Session["MaVaiTro"] != 1)
            {
                return RedirectToAction("Login", "Home");
            }
            return View();
        }
        public ActionResult ThongTinCaNhan()
        {
            if (Session["MaGV"] == null)
            {
                return RedirectToAction("Login", "Home");
            }

            string maGV = Session["MaGV"].ToString();
            var giangVien = db.GiangViens.FirstOrDefault(gv => gv.MaGV == maGV);

            if (giangVien == null)
            {
                return HttpNotFound("Không tìm thấy thông tin giảng viên.");
            }

            return View(giangVien);
        }
        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Login", "Home");
        }
    }
}

Controllers/KhoasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UniSchedule.Models;

namespace UniSchedule.Controllers
{
    public class KhoasController : Controller
    {
        private XepLichGiangVienEntities db = new XepLichGiangVienEntities();
        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            if (Session["MaVaiTro"] == null || (int)Session["MaVaiTro"] != 2)
            {
                // Không phải GiaoVu thì chuyển về trang login
                filterContext.Result = RedirectToAction("Login", "Home");
            }
            base.OnActionExecuting(filterContext);
        }
        // GET: Khoas
        public ActionResult Index()
        {
            return View(db.Khoas.ToList());
        }

        // GET: Khoas/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Khoa khoa = db.Khoas.Find(id);
            if (khoa == null)
            {
                return HttpNotFound();
            }
            return View(khoa);
        }

        // GET: Khoas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Khoas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaKhoa,TenKhoa")] Khoa khoa)
        {
            if (ModelState.IsValid)
            {
                db.Khoas.Add(khoa);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(khoa);
        }

        // GET: Khoas/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Khoa khoa = db.Khoas.Find(id);
            if (khoa == null)
            {
                return HttpNotFound();
            }
            return View(khoa);
        }

        // POST: Khoas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaKhoa,TenKhoa")] Khoa khoa)
        {
            if (ModelState.IsValid)
            {
                db.Entry(khoa).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(khoa);
        }

        // GET: Khoas/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Khoa khoa = db.Khoas.Find(id);
            if (khoa == null)
            {
                return HttpNotFound();
            }
            return View(khoa);
        }

        // POST: Khoas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Khoa khoa = db.Khoas.Find(id);
            db.Khoas.Remove(khoa);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/PhongHocsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UniSchedule.Models;

namespace XepLichGiangVien.Controllers
{
    public class PhongHocsController : Controller
    {
        private XepLichGiangVienEntities db = new XepLichGiangVienEntities();
        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            if (Session["MaVaiTro"] == null || (int)Session["MaVaiTro"] != 2)
            {
                // Không phải GiaoVu thì chuyển về trang login
                filterContext.Result = RedirectToAction("Login", "Home");
            }
            base.OnActionExecuting(filterContext);
        }
        // GET: PhongHocs
        public ActionResult Index()
        {
            return View(db.PhongHocs.ToList());
        }

        // GET: PhongHocs/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhongHoc phongHoc = db.PhongHocs.Find(id);
            if (phongHoc == null)
            {
                return HttpNotFound();
            }
            return View(phongHoc);
        }

        // GET: PhongHocs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PhongHocs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaPhong,TenPhong,SoLuongChoNgoi")] PhongHoc phongHoc)
        {
            if (String.IsNullOrEmpty(phongHoc.MaPhong) || String.IsNullOrEmpty(phongHoc.TenPhong))
            {
                if (String.IsNullOrEmpty(phongHoc.MaPhong)){
                    ModelState.AddModelError("MaPhong", "Mã Phòng trống.");
                }
                if (String.IsNullOrEmpty(phongHoc.TenPhong))
                {
                    ModelState.AddModelError("TenPhong", "Tên phòng trống.");
                }
                return View(phongHoc);
            }
            if (ModelState.IsValid)
            {
                db.PhongHocs.Add(phongHoc);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(phongHoc);
        }

        // GET: PhongHocs/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhongHoc phongHoc = db.PhongHocs.Find(id);
            if (phongHoc == null)
            {
                return HttpNotFound();
            }
            return View(phongHoc);
        }

        // POST: PhongHocs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaPhong,TenPhong,SoLuongChoNgoi")] PhongHoc phongHoc)
        {
            if (ModelState.IsValid)
            {
                db.Entry(phongHoc).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(phongHoc);
        }

        // GET: PhongHocs/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhongHoc phongHoc = db.PhongHocs.Find(id);
            if (phongHoc == null)
            {
                return HttpNotFound();
            }
            return View(phongHoc);
        }

        // POST: PhongHocs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            PhongHoc phongHoc = db.PhongHocs.Find(id);
            db.PhongHocs.Remove(phongHoc);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Home/GiangVien.cshtml
@{
    ViewBag.Title = "Trang Giảng Viên";
}

<!-- Thêm link FontAwesome nếu chưa có -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" />

<div class="container d-flex justify-content-center align-items-center min-vh-100">
    <div class="card shadow-lg p-4" style="width: 100%; max-width: 500px; border-radius: 1rem;">
        <div class="text-center mb-4">
            <h2 class="fw-bold">Chào mừng Giảng Viên</h2>
            <p class="text-muted">Vui lòng chọn chức năng</p>
        </div>

        <div class="list-group">
            <a href="@Url.Action("XemLich", "LichDays")" class="list-group-item list-group-item-action d-flex align-items-center gap-2">
                <i class="fas fa-calendar-alt fa-lg text-primary"></i> Xem lịch dạy cá nhân
            </a>
            <a href="@Url.Action("Index", "LichDays")" class="list-group-item list-group-item-action d-flex align-items-center gap-2">
                <i class="fas fa-calendar-alt fa-lg text-danger"></i> Xem Thời Khóa Biểu
            </a>
            <a href="@Url.Action("ThongTinCaNhan", "Home")" class="list-group-item list-group-item-action d-flex align-items-center gap-2">
                <i class="fas fa-user fa-lg text-success"></i> Thông tin cá nhân
            </a>
        </div>

        <div class="text-center mt-4">
            <a href="@Url.Action("Logout", "Home")" class="btn btn-outline-danger w-100">
                <i class="fas fa-sign-out-alt"></i> Đăng xuất
            </a>
        </div>
    </div>
</div>

<style>
    .list-group-item {
        transition: background-color 0.3s, transform 0.3s;
        border: none;
        border-bottom: 1px solid #eee;
    }

        .list-group-item:hover {
            background-color: #f8f9fa;
            transform: translateX(5px);
        }

    .card {
        background: #ffffff;
    }
</style>

Views/Home/GiaoVu.cshtml
@model IEnumerable<UniSchedule.Models.LichDay>

@{
    ViewBag.Title = "Trang Giáo Vụ";
}

<!-- Thêm link FontAwesome nếu chưa có -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" />

<div class="container d-flex justify-content-center align-items-center min-vh-100">
    <div class="card shadow-lg p-4" style="width: 100%; max-width: 500px; border-radius: 1rem;">
        <div class="text-center mb-4">
            <h2 class="fw-bold">Chào mừng Giáo Vụ</h2>
            <p class="text-muted">Vui lòng chọn chức năng</p>
        </div>

        <div class="list-group">
            <a href="@Url.Action("Index", "Khoas")" class="list-group-item list-group-item-action d-flex align-items-center gap-2">
                <i class="fas fa-building fa-lg text-primary"></i> Quản lý Khoa
            </a>
            <a href="@Url.Action("Index", "GiangViens")" class="list-group-item list-group-item-action d-flex align-items-center gap-2">
                <i class="fas fa-chalkboard-teacher fa-lg text-success"></i> Quản lý Giảng viên
            </a>
            <a href="@Url.Action("Index", "LopHocPhans")" class="list-group-item list-group-item-action d-flex align-items-center gap-2">
                <i class="fas fa-book-open fa-lg text-warning"></i> Quản lý Lớp học phần
            </a>
            <a href="@Url.Action("Index", "PhongHocs")" class="list-group-item list-group-item-action d-flex align-items-center gap-2">
                <i class="fas fa-door-open fa-lg text-info"></i> Quản lý Phòng học
            </a>
            <a href="@Url.Action("Index", "PhanCongGiangDays")" class="list-group-item list-group-item-action d-flex align-items-center gap-2">
                <i class="fas fa-chalkboard-teacher fa-lg text-warning"></i> Phân Công Giảng Dạy
            </a>
            <a href="@Url.Action("Index", "LichDays")" class="list-group-item list-group-item-action d-flex align-items-center gap-2">
                <i class="fas fa-calendar-alt fa-lg text-danger"></i> Xếp Thời Khóa Biểu
            </a>
            <a href="@Url.Action("XemLich", "LichDays")" class="list-group-item list-group-item-action d-flex align-items-center gap-2">
                <i class="fas fa-calendar-check fa-lg text-primary"></i> Xem Lịch Cá Nhân
            </a>
            <a href="@Url.Action("Index", "TaiKhoans")" class="list-group-item list-group-item-action d-flex align-items-center gap-2">
                <i class="fas fa-user-cog fa-lg text-secondary"></i> Quản lý Tài khoản
            </a>
        </div>

        <div class="text-center mt-4">
            <a href="@Url.Action("Logout", "Home")" class="btn btn-outline-danger w-100">
                <i class="fas fa-sign-out-alt"></i> Đăng xuất
            </a>
        </div>
    </div>
</div>

<style>
    .list-group-item {
        transition: background-color 0.3s, transform 0.3s;
        border: none;
        border-bottom: 1px solid #eee;
    }

        .list-group-item:hover {
            background-color: #f8f9fa;
            transform: translateX(5px);
        }

    .card {
        background: #ffffff;
    }
</style>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Trang chủ";
    Layout = "~/Views/Shared/_Layout.cshtml"; // hoặc để trống nếu bạn không dùng layout
}

<style>
    body {
        background: url('https://baodanang.vn/dataimages/202111/original/images1630532_3__H_N_.jpg') no-repeat center center fixed;
        background-size: cover;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }

    .homepage-container {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        height: 80vh;
        text-align: center;
        background: rgba(255, 255, 255, 0.7); /* Để nền mờ đi, dễ đọc chữ */
        padding: 20px;
        border-radius: 10px;
    }

    .homepage-title {
        font-size: 3rem;
        margin-bottom: 0.5rem;
        color: #333;
    }

    .homepage-subtitle {
        font-size: 1.2rem;
        margin-bottom: 2rem;
        color: #666;
    }

    .login-button {
        padding: 0.75rem 2rem;
        font-size: 1.2rem;
        background-color: #007bff;
        color: white;
        border: none;
        border-radius: 8px;
        text-decoration: none;
        transition: background-color 0.3s ease;
    }

        .login-button:hover {
            background-color: #0056b3;
            color: white;
        }
</style>

<div class="homepage-container">
    <img src="https://inkythuatso.com/uploads/thumbnails/800/2021/12/logo-dai-hoc-bach-khoa-da-nang-inkythuatso-01-21-09-26-41.jpg" alt="Logo" style="width: 150px; height: auto; margin-bottom: 20px;" />
    <div class="homepage-title">Ứng Dụng Xếp Lịch Tự Động</div>
    <div class="homepage-subtitle">Trường Đại Học Bách Khoa - Đại Học Đà Nẵng</div>

    @if (Session["TenDangNhap"] != null)
    {
        @Html.ActionLink(
            "Đăng xuất",
            "Logout",
            "Home",
            routeValues: null,
            htmlAttributes: new { @class = "login-button" }
        )
    }
    else
    {
        @Html.ActionLink(
            "Đăng nhập",
            "Login",
            "Home",
            routeValues: null,
            htmlAttributes: new { @class = "login-button" }
        )
    }
</div>

Views/Home/PhongDaoTao.cshtml
@{
    ViewBag.Title = "Phòng Đào Tạo";
}

<!-- FontAwesome icon -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" />

<div class="container d-flex justify-content-center align-items-center min-vh-100">
    <div class="card shadow-lg p-4" style="width: 100%; max-width: 500px; border-radius: 1rem;">
        <div class="text-center mb-4">
            <h2 class="fw-bold">Phòng Đào Tạo</h2>
            <p class="text-muted">Vui lòng chọn chức năng</p>
        </div>

        <div class="list-group">
            <a href="@Url.Action("Index", "Khoas")" class="list-group-item list-group-item-action d-flex align-items-center gap-2">
                <i class="fas fa-building text-primary"></i> Quản lý Khoa
            </a>
            <a href="@Url.Action("Index", "GiangViens")" class="list-group-item list-group-item-action d-flex align-items-center gap-2">
                <i class="fas fa-user-tie text-success"></i> Quản lý Giảng viên
            </a>
            <a href="@Url.Action("Index", "LopHocPhans")" class="list-group-item list-group-item-action d-flex align-items-center gap-2">
                <i class="fas fa-book text-warning"></i> Quản lý Lớp học phần
            </a>
            <a href="@Url.Action("Index", "PhongHocs")" class="list-group-item list-group-item-action d-flex align-items-center gap-2">
                <i class="fas fa-door-open text-info"></i> Quản lý Phòng học
            </a>
            <a href="@Url.Action("Index", "PhanCongGiangDays")" class="list-group-item list-group-item-action d-flex align-items-center gap-2">
                <i class="fas fa-chalkboard-teacher fa-lg text-warning"></i> Phân Công Giảng Dạy
            </a>
            <a href="@Url.Action("Index", "LichDays")" class="list-group-item list-group-item-action d-flex align-items-center gap-2">
                <i class="fas fa-calendar-alt text-danger"></i> Xếp Lịch Dạy
            </a>
            <a href="@Url.Action("Index", "TaiKhoans")" class="list-group-item list-group-item-action d-flex align-items-center gap-2">
                <i class="fas fa-user-cog text-secondary"></i> Quản lý Tài khoản
            </a>
        </div>

        <div class="text-center mt-4">
            <a href="@Url.Action("Logout", "Home")" class="btn btn-outline-danger w-100">
                <i class="fas fa-sign-out-alt"></i> Đăng xuất
            </a>
        </div>
    </div>
</div>

<style>
    .list-group-item {
        transition: background-color 0.3s, transform 0.3s;
        border: none;
        border-bottom: 1px solid #eee;
    }

        .list-group-item:hover {
            background-color: #f8f9fa;
            transform: translateX(5px);
        }

    .card {
        background: #ffffff;
    }
</style>

Views/Home/ThongTinCaNhan.cshtml
@model UniSchedule.Models.GiangVien

@{
    ViewBag.Title = "Thông Tin Cá Nhân";
}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6 col-lg-5">
            <!-- Giới hạn chiều rộng đẹp hơn -->
            <div class="card shadow-lg rounded-4">
                <div class="card-header bg-primary text-white text-center rounded-top-4">
                    <h4 class="mb-0"><i class="bi bi-person-vcard"></i> Thông Tin Cá Nhân</h4>
                </div>
                <div class="card-body px-4 py-3">
                    <dl class="row gy-2">
                        <dt class="col-5 text-muted text-end">Họ tên</dt>
                        <dd class="col-7">@Model.TenGV</dd>

                        <dt class="col-5 text-muted text-end">Email</dt>
                        <dd class="col-7">@Model.Email</dd>

                        <dt class="col-5 text-muted text-end">Số điện thoại</dt>
                        <dd class="col-7">@Model.SoDienThoai</dd>

                        <dt class="col-5 text-muted text-end">Khoa</dt>
                        <dd class="col-7">@Model.Khoa.TenKhoa</dd>
                    </dl>
                </div>
                <div class="card-footer bg-light text-end rounded-bottom-4">
                    <a href="@Url.Action("GiangVien", "Home")" class="btn btn-outline-secondary">
                        <i class="bi bi-arrow-left-circle"></i> Quay lại
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>